In [2]:
import numpy as np

In [3]:
print("1D array")
a=np.array([1,2,3,4])
print(a)

1D array
[1 2 3 4]


In [4]:
print("2D array ")
b=np.array([[1,2,3,4,],[4,5,6,7]])
print(b)

2D array 
[[1 2 3 4]
 [4 5 6 7]]


In [5]:
print("3D array")
c=np.array([[1,3,5,6],[3,3,4,5],[5,7,7,8]])
print(c)

3D array
[[1 3 5 6]
 [3 3 4 5]
 [5 7 7 8]]


In [7]:
type(a)

numpy.ndarray

In [8]:
print(a.size)
print(b.size)
print(c.size)

4
8
12


In [10]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
int32
int32


In [11]:
d=np.array([[2.3,4.5,6.7],[2.3,4.5,7.7],[2.3,4.5,6.7]])
print(d)

[[2.3 4.5 6.7]
 [2.3 4.5 7.7]
 [2.3 4.5 6.7]]


In [13]:
type(d)

numpy.ndarray

In [14]:
print(d.dtype)

float64


In [17]:
d.transpose()

array([[2.3, 2.3, 2.3],
       [4.5, 4.5, 4.5],
       [6.7, 7.7, 6.7]])

# np.empty((rows,cols),dtype)


In [19]:
np.empty((4,4),dtype=int)

array([[      0,       0,       0,       0],
       [      0,       0,       0,       0],
       [      0,       0,    1908,       0],
       [      0, 6029363,       0, 7536716]])

In [25]:
np.empty((4,4),dtype=int)

array([[      0,       0,       0,       0],
       [      0,       0,       0,       0],
       [      0,       0,    1924,       0],
       [      0, 6029420,       0, 7340141]])

In [27]:
x=np.ones((6),dtype=int)
x

array([1, 1, 1, 1, 1, 1])

In [31]:
y=np.zeros((3,4) ,dtype=float)
y

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
x=np.ones((6,7),dtype=bool)
x

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [35]:
x=np.ones((6,7),dtype=str)
x

array([['1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1']], dtype='<U1')

In [37]:
x=np.zeros((8,9),dtype=bool)
x

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False]])

In [40]:
x=np.ones((8,9),dtype=str)
x

array([['1', '1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1', '1']], dtype='<U1')

# np.arange(start,end,step)

In [19]:
a=np.arange(1,28)                ## it print the numbers starting fron 1 and end at 30-1
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]


In [8]:
b=np.arange(1,30,2)   ##it print numbers from 1 to 30 by skiping 2 numbers 
print(b)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]


In [27]:
 c=np.arange(1,50,2) ##it print numbers from 1 to 50 ny sikping the 5 number from the staring number
print(c)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


# arr.reshape((rows,cols))

In [22]:
a=a.reshape((3,9))
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [24]:
b=a.flatten()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [29]:
c=c.reshape(5,5)
c

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [31]:
c=c.ravel()
c

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])